spring:
  application:
    name: auth_ms

  # JPA configuration
  jpa.:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # flyway
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:db/migration
    url: ${DB_URL}
    schemas: qms_auth
    user: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: ${REDIS_ENABLE_SSL}
  docker:
    compose:
      enabled: false

server:
  port: 80

logging:
  level:
    root: DEBUG

quemistry:
  cognito:
    url: ${COGNITO_URL}
  session:
    timeout: 86400
  cors:
    allowed:
      origin: ${QUEMISTRY_CLIENT_WEB_URL}
