spring:
  application:
    name: auth_ms

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true
  docker:
    compose:
      enabled: false

server:
  port: 80

quemistry:
  cognito:
    url: ${COGNITO_URL}
  session:
    timeout: 86400
  cors:
    allowed:
      origin: ${QUEMISTRY_CLIENT_WEB_URL}
